# Generated by cpp11: do not edit by hand

phi_to_theta <- function(phi, transformation_type, theta_min, theta_max) {
  .Call(`_dj11_phi_to_theta`, phi, transformation_type, theta_min, theta_max)
}

theta_to_phi <- function(theta, transformation_type, theta_min, theta_max) {
  .Call(`_dj11_theta_to_phi`, theta, transformation_type, theta_min, theta_max)
}

mcmc <- function(theta_init, transform_type, theta_min, theta_max, data, iterations, ll, lp) {
  .Call(`_dj11_mcmc`, theta_init, transform_type, theta_min, theta_max, data, iterations, ll, lp)
}
