# Generated by cpp11: do not edit by hand

mcmc <- function(theta_init, theta_names, transform_type, theta_min, theta_max, blocks, n_unique_blocks, data, burnin, samples, ll_f, lp_f, target_acceptance, misc) {
  .Call(`_dj11_mcmc`, theta_init, theta_names, transform_type, theta_min, theta_max, blocks, n_unique_blocks, data, burnin, samples, ll_f, lp_f, target_acceptance, misc)
}
